#!/bin/bash
abs_path="/usr/share/c2rprox"

cd $abs_path

if [ "$(id -u)" != "0" ]; then
	echo "Run it as root user"
	exit 1
fi

function help {
	echo "Usage: start|stop"
	echo "Config file: $abs_path/targets"
	echo "Log file: $abs_path/c2rprox.log"
	echo "Log file: $abs_path/output.log"
	
}

function start {
	pid=$(pgrep -f c2rprox)
	
	if [ "$pid" != "" ]; then 
		echo "Daemon already running, pid : $pid"; 
		exit 1
	fi
	
	nohup ./c2rprox &> output.log &
	
	pid=$(pgrep -f c2rprox)
	
	if [ "$pid" != "" ]; then 
		echo "Daemon running, pid : $pid"; 
		else
		echo "Problem : daemon not running"
	fi
}

function stop {
	pid=$(pgrep -f c2rprox)
	
	if [ "$pid" != "" ]; then 
			kill -9 $pid
			sleep 2
		else
			echo "Daemon already stopped"
			exit 1
	fi
	
	pid=$(pgrep -f c2rprox)
	if [ "$pid" != "" ]; then 
	kill -9 $pid
			echo "Problem : daemon not stopped, pid : $pid"
		else
			echo "Daemon stopped"
	fi
}

case $1 in 
	"start")
	 start;
	;;
	"stop")
	 stop;
	;;
	*)
	help
	;;
esac